### ISSUE TITLE
Sidebar not found

### ISSUE THREAD

**Issue by diip3sh** [linuxmobile/SilentFox#1]
👋🏻 I was trying to implement the chrome css in firefox everything works fine but the current tab is not visible in the and how can I go back and forth in website there is no readme.md file can you help me...

![image](https://github.com/linuxmobile/SilentFox/assets/99866329/3ca43be5-b088-487f-8800-7cda6aedeffc)

**Comment by linuxmobile** [comment]
> how can I go back and forth in website there is no readme.md file can you help me...

###  You should wait for me to publish the readme.
